Added Dark Mode as a component
StafflinePeoplePlus/peopleplus-components pull request #162
Opened 2023-05-10 12:38 UTC by ArunPurewal1994

Added dark mode/light mode button

2023-05-10 13:05 UTC, jamesbirtles requested changes

2023-05-10 13:05 UTC, jamesbirtles commented on src/lib/DarkMode.svelte
> +<button
We should create an issue to create a Switch component, then use that here. Theres a few accessibility requirements to consider for switches that this currently doesn't handle - https://www.w3.org/WAI/ARIA/apg/patterns/switch/

Unfortunately the switch in headless ui (https://captaincodeman.github.io/svelte-headlessui/switch/) is not implemented yet - might be a good contribution to make

2023-05-10 13:05 UTC, jamesbirtles commented on src/lib/accordion/Accordion.svelte
> -		'border-gray-200 bg-white',
i'd rather keep the background on this, a transparent accordion would be weird imo

2023-05-10 13:05 UTC, jamesbirtles commented on src/routes/DarkMode/+page.svelte
> +	const usage = '<DarkMode />';
Even though its a pretty basic usage, I still think its worth having the extra component and importing usage using `?raw`
e.g.
```
import ExampleDarkMode from "./ExampleDarkMode.svelte";
import usage from "./ExampleDarkMode.svelte?raw";
```

2023-05-10 13:12 UTC, jamesbirtles commented on src/app.css
> +	@apply bg-white dark:bg-gray-900 dark:text-white;
it's worth reading this page - https://tailwindcss.com/docs/reusing-styles
essentially `@apply` should be avoided

2023-05-10 14:00 UTC, ArunPurewal1994 commented on src/lib/DarkMode.svelte
> +	let dark: boolean;
I've specified it as boolean as this part of the code here: 
dark = document.documentElement.classList.contains('dark');  cannot be determined as false as it's initial state

2023-05-10 14:43 UTC, jamesbirtles commented on src/lib/DarkMode.svelte
> +	let dark: boolean;
the problem is that on the server the onMount will never be run, and so I think the variable will technically be undefined if we don't initialise it to something

2023-05-10 15:46 UTC, danny-people-plus commented on src/app.d.ts
>  		context: {
```<never>```
Instead of
```<any>```
?

2023-05-11 09:50 UTC, jamesbirtles requested changes
A few more comments. I also clicked the button to merge uat into this PR, so you'll want to `git pull` before making any further changes

2023-05-11 09:50 UTC, jamesbirtles commented on src/app.html
> +	<body class="h-full bg-white dark:bg-gray-900 text-gray-900 dark:text-white">
the background is set on the html tag above to `bg-gray-100`. The duplication should be removed, and i'd prefer the background color remain the same as it was before

2023-05-11 09:50 UTC, jamesbirtles commented on src/lib/DarkMode.svelte
> +	let hidden = true;
whats the reason for this component being hidden until mounted?

2023-05-11 09:50 UTC, jamesbirtles commented on src/routes/DarkMode/ExampleDarkMode.svelte
> +	import DarkMode from '$lib/DarkMode.svelte';
```suggestion
	import { DarkMode } from '$lib';
```

2023-05-11 09:50 UTC, jamesbirtles commented on src/routes/+layout.svelte
> +			<div class="h-full p-6 border border-gray-200 rounded-md overflow-y-auto">
i don't think bg-white should be removed

2023-05-11 13:08 UTC, jamesbirtles approved these changes

2023-05-11 13:57 UTC, merged