Basic Footer Component
StafflinePeoplePlus/peopleplus-components pull request #201
Opened 2023-05-12 11:20 UTC by ArunPurewal1994

Added in the basic footer component, with just links and the copyright. 
Will flesh it out more and add more functionality, such as if there needs to be a logo, or social media links etc.

2023-05-12 11:34 UTC, danny-people-plus commented on src/lib/footer/FooterCopyright.svelte
Could this just be Copyright.svelte?

2023-05-12 11:34 UTC, danny-people-plus commented on src/lib/footer/FooterItem.svelte
Could this just be ListItem.svelte?

2023-05-12 11:35 UTC, danny-people-plus commented on src/lib/footer/FooterTitle.svelte
Could this just be Title.svelte?

2023-05-12 11:37 UTC, danny-people-plus commented on src/lib/footer/Footer.svelte
Number of slots so we can change view depending on screen size?

2023-05-12 11:38 UTC, danny-people-plus commented on src/routes/Footer/ExampleFooter.svelte
&copy; instead of ©
&trade; instead of ™

2023-05-12 13:05 UTC, jamesbirtles requested changes
<img width="1485" alt="CleanShot 2023-05-12 at 13 50 23@2x" src="https://github.com/StafflinePeoplePlus/peopleplus-components/assets/3743418/56575663-0917-4c1e-9d2b-1c4bd95dbd1f">

The links appear to be stacked on top of each other rather than inline like they were before.
Also the footer at the bottom is now empty

2023-05-12 13:05 UTC, jamesbirtles commented on src/lib/footer/Footer.svelte
I don't believe you can have an unknown number of slots as you can't dynamically name a slot, here's a repl with an attempt https://svelte.dev/repl/ced529d50b9f493d808d96881f99ddb8?version=3.59.1

2023-05-12 13:17 UTC, danny-people-plus commented on src/lib/footer/Footer.svelte
Fair enough, could just stick with the three slot approach as used in the NavBar or pick another number.

2023-05-12 13:19 UTC, ArunPurewal1994 commented on src/lib/footer/Footer.svelte
managed to get the copyright and links in their own slot - I think 3 would be max but currently only have 2

2023-05-12 13:59 UTC, danny-people-plus requested changes

2023-05-12 13:59 UTC, danny-people-plus commented on src/lib/footer/Footer.svelte
> +		<ul
This is assuming we want a list in the last slot, we may not.

2023-05-30 15:03 UTC, jamesbirtles requested changes
> Will flesh it out more and add more functionality, such as if there needs to be a logo, or social media links etc.

Is this a separate task then - and if so is there an issue for this?

> Also the footer at the bottom is now empty

This doesn't seem to have been resolved since my last review

2023-06-20 14:54 UTC, closed without merging